version: '3.7'
services:
  activemq:
    image: activemq
    build: ./activemq
    ports: 
      - 61616:61616
      - 5672:5672
      - 61613:61613
      - 61614:61614
      - 8161:8161
    deploy:
      replicas: 1  # 從這個image開5個instance
  client:
    image: mqclient
    build: ./client
    environment:
      - ACTIVEMQ_HOST=activemq
    deploy:
      replicas: 3  # 從這個image開5個instance

#佈署
#docker stack deploy -c docker-compose.yml airflow_cluster

#移除佈署
#docker stack rm airflow_cluster